## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file lecture_notes.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_328 = Integer(328); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_29 = Integer(29); _sage_const_59 = Integer(59); _sage_const_296 = Integer(296); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_19 = Integer(19); _sage_const_25 = Integer(25); _sage_const_63 = Integer(63); _sage_const_133 = Integer(133); _sage_const_132 = Integer(132); _sage_const_206 = Integer(206); _sage_const_453 = Integer(453); _sage_const_68 = Integer(68); _sage_const_239 = Integer(239); _sage_const_175 = Integer(175); _sage_const_151 = Integer(151); _sage_const_179 = Integer(179); _sage_const_230 = Integer(230); _sage_const_236 = Integer(236); _sage_const_353 = Integer(353); _sage_const_199 = Integer(199); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_347 = Integer(347); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_58 = Integer(58); _sage_const_33 = Integer(33); _sage_const_18 = Integer(18); _sage_const_36 = Integer(36); _sage_const_109 = Integer(109); _sage_const_121 = Integer(121); _sage_const_126 = Integer(126); _sage_const_393 = Integer(393); _sage_const_124 = Integer(124); _sage_const_125 = Integer(125); _sage_const_283 = Integer(283); _sage_const_91 = Integer(91); _sage_const_103 = Integer(103); _sage_const_106 = Integer(106); _sage_const_94 = Integer(94); _sage_const_438 = Integer(438); _sage_const_413 = Integer(413); _sage_const_309 = Integer(309); _sage_const_17 = Integer(17); _sage_const_14 = Integer(14); _sage_const_89 = Integer(89)## This file (lecture_notes.sagetex.sage) was *autogenerated* from lecture_notes.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('lecture_notes', version='2019/11/14 v3.4', version_check=True)
try:
 _st_.current_tex_line = _sage_const_11 
 _st_.doctest(_sage_const_0 , r"""
    sage: type(ZZ)
  
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_13 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.doctest(_sage_const_1 , r"""
    sage: a,b = ZZ(4), 4
    sage: type(a) == type(b)
    sage: a == b
  
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_29 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.doctest(_sage_const_2 , r"""
    sage: 2/3
    sage: type(2/3)
    sage: 1/1
    sage: type(1/1)
  
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_21 
 _st_.doctest(_sage_const_3 , r"""
    sage: def divides0(a,b):
    ....:     return (a/b).is_integer()
    sage: divides0(5,2)
    sage: divides0(6,3)
  
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_26 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.doctest(_sage_const_4 , r"""
        sage: def divides0(a,b):
        ....:     return (a/b).is_integer()
        sage: def divides1(a,b):
        ....:     return a % b == 0
        sage: def divides2(a,b):
        ....:     return (a//b)*b == a
        sage: def divides3(a,b):
        ....:     return (a/b).denom() == 1
        sage: def divides4(a,b): #there is room to improve
        ....:     if a == 0:
        ....:         return True
        ....:     b *= sign(b)
        ....:     if b == 1:
        ....:         return True
        ....:     q = b
        ....:     a *= sign(a)
        ....:     while q <= a:
        ....:         q <<= 1
        ....:     while a > b:
        ....:         q >>= 1
        ....:         a -= q
        ....:         a *= sign(a)
        ....:     return a == 0 or a == b

      
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.current_tex_line = _sage_const_103 
 _st_.doctest(_sage_const_5 , r"""
  sage: k = 15
  ....: P = Poset((Set([2..k]), lambda a,b: b % a == 0))
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.plot(_sage_const_0 , format='png', _p_=P.plot(talk=True))
except:
 _st_.goboom(_sage_const_109 )
try:
 _st_.current_tex_line = _sage_const_124 
 _st_.doctest(_sage_const_6 , r"""
    sage: len(P.cover_relations_graph().edges())
  
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_133 
 _st_.doctest(_sage_const_7 , r"""
      sage: def edges_in_div_hasse(S):
      ....:     count = 0
      ....:     L = list(S)
      ....:     L.sort(reverse=True)
      ....:     for i in range(1,len(L)):
      ....:         S = set()
      ....:         for j in range(i-1,-1,-1):
      ....:             if L[j] % L[i] == 0:
      ....:                 direct = True
      ....:                 for k in S:
      ....:                     if L[j] % L[k] == 0:
      ....:                         direct = False
      ....:                         break
      ....:                 if direct:
      ....:                     S.add(j)
      ....:                     count += 1
      ....:     return count
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_151 )
try:
 _st_.current_tex_line = _sage_const_230 
 _st_.doctest(_sage_const_8 , r"""
  sage: P1 = plot(x/log(x), (2, 200), scale='semilogy', \
  ....:     fill=lambda x: prime_pi(x),fillcolor='red')
  ....: P2 = plot(1.13*log(x), (2, 200), \
  ....:     fill=lambda x: nth_prime(x)/floor(x), fillcolor='red')
  ....: P = graphics_array([P1, P2])
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_236 )
try:
 _st_.current_tex_line = _sage_const_239 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=P,figsize=[_sage_const_8 ,_sage_const_4 ])
except:
 _st_.goboom(_sage_const_239 )
try:
 _st_.current_tex_line = _sage_const_26 
 _st_.doctest(_sage_const_9 , r"""
      sage: def residue_sets(S,m):
      ....:     rs = {}
      ....:     for e in S:
      ....:         r = e % m
      ....:         if r in rs.keys():
      ....:             rs[r].add(e)
      ....:         else:
      ....:             rs[r] = set([e])
      ....:     return rs
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.doctest(_sage_const_10 , r"""
  sage: P  = points([(k,euler_phi(k)) for k in range(1,1001)])
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_94 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=P)
except:
 _st_.goboom(_sage_const_94 )
try:
 _st_.current_tex_line = _sage_const_106 
 _st_.doctest(_sage_const_11 , r"""
    # according to the definition
    sage: def ephi_01(m):
    ....:     p = 0
    ....:     for i in range(1,m):
    ....:         p += gcd(i,m) == 1
    ....:     return p

    #according to the previous note
    sage: def ephi_02(m):
    ....:     p = 1
    ....:     for (a,b) in factor(m):
    ....:         p *= a^(b-1)*(a-1)
    ....:     return p

    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_121 )
try:
 _st_.current_tex_line = _sage_const_175 
 _st_.doctest(_sage_const_12 , r"""
    sage: def lin_cong(a,b,m):
    ....:     (d,x,y) = xgcd(a,m)
    ....:     return x % m/d
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_179 )
try:
 _st_.current_tex_line = _sage_const_199 
 _st_.doctest(_sage_const_13 , r"""
    sage: def modinv(a,m):
    ....:     (d,x,y) = xgcd(a,m)
    ....:     if d == 1:
    ....:         return x % m
    ....:     else:
    ....:         return None
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_206 )
try:
 _st_.current_tex_line = _sage_const_283 
 _st_.doctest(_sage_const_14 , r"""
    sage: def chinese(C,M):
    ....:     if len(C) != len(M):
    ....:         return None
    ....:     c, m = C[0], M[0]
    ....:     for i in range(1, len(C)):
    ....:         (g, u, v) = xgcd(m, M[i])
    ....:         if g != 1:
    ....:             return None
    ....:         c = (c*M[i]*v + C[i]*m*u)
    ....:         m *= M[i]
    ....:         c %= m
    ....:     return c
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_296 )
try:
 _st_.current_tex_line = _sage_const_309 
 _st_.doctest(_sage_const_15 , r"""
    sage: def lin_cong_sys(A,B,M):
    ....:     if len(A) != len(B) or len(B) != len(C):
    ....:         return None # should raise some exception
    ....:     c, m = 0, 1
    ....:     for  i in range(len(A)):
    ....:         #sole the ith equation
    ....:         (d, x, _) = xgcd(A[i], M[i])
    ....:         if B[i] % d != 0:
    ....:             return None
    ....:         x = (x*B[i]/d) % M[i]
    ....:         #add to the solution
    ....:         (g, u, v) = xgcd(m, M[i])
    ....:         if (c-x) % g != 0:
    ....:             return None
    ....:         c = (c*M[i]*v + x*m*u)/g
    ....:         m *= M[i]
    ....:         c %= m
    ....:     return c
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_328 )
try:
 _st_.current_tex_line = _sage_const_347 
 _st_.doctest(_sage_const_16 , r"""
    sage: def quadratic_residues(m):
    ....:     qrs = set()
    ....:     for i in range(m):
    ....:         qrs.add(i^2 % m)
    ....:     return qrs
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_353 )
try:
 _st_.current_tex_line = _sage_const_393 
 _st_.doctest(_sage_const_17 , r"""
    sage: class RSA(object):
    ....:     #this is just a dummy implementation, not for actual use
    ....:     def __init__(self, length):
    ....:         # uniformly choosen prime is not a good idea in real life
    ....:         p = random_prime(2^(length-2), lbound=2^(length-3))
    ....:         q = random_prime(2^(length+2), lbound=2^(length+1))
    ....:         self.__n = p*q
    ....:         self.__phin = (p-1)*(q-1)
    ....:         self.__e = 3 #should choose this more carefully
    ....:         while gcd(self.__e, self.__phin) != 1:
    ....:             self.__e += 2
    ....:         self.__d = inverse_mod(self.__e, self.__phin)
    ....:     def public_key(self):
    ....:         return (self.__n, self.__e)
    ....:     @staticmethod
    ....:     def encrypt(pubkey, message):
    ....:         return power_mod(message, pubkey[1], pubkey[0])
    ....:     def decrypt(self, secret):
    ....:         return power_mod(secret, self.__d, self.__n)
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_413 )
try:
 _st_.current_tex_line = _sage_const_438 
 _st_.doctest(_sage_const_18 , r"""
    sage: class DH_participant(object):
    ....:     def __init__(self, p, g):
    ....:         self.__p = p
    ....:         self.__g = g
    ....:         self.__x = randint(1, p-1)
    ....:     def get_pub(self):
    ....:         return power_mod(self.__g, self.__x, self.__p)
    ....:     def calculate_common_key(self, pub_of_other):
    ....:         return power_mod(pub_of_other, self.__x, self.__p)
    ....: Alice = DH_participant(65537, 2)
    ....: Bob   = DH_participant(65537, 2)
    ....: #common key
    ....: Alice.calculate_common_key(Bob.get_pub())
    ....: Bob.calculate_common_key(Alice.get_pub())
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_453 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.doctest(_sage_const_19 , r"""
      sage: class my_poly(object):
      ....:     def __init__(self, F):
      ....:         self.__coeffs = F
      ....:     def deg(self):
      ....:         d = len(self.__coeffs)-1
      ....:         while d >= 0 and self.__coeffs[d] == 0:
      ....:             d -= 1
      ....:         if d >= 0:
      ....:             return d
      ....:         return -Infinit
      ....:     def __add__(self, other):
      ....:         L, i = [], 0
      ....:         while i < len(self.__coeffs) and i < len(other.__coeffs):
      ....:             L.append(self.__coeffs[i] + other.__coeffs[i])
      ....:             i += 1
      ....:         while i < len(self.__coeffs):
      ....:             L.append(self.__coeffs[i])
      ....:             i += 1
      ....:         while i < len(other.__coeffs):
      ....:             L.append(other.__coeffs[i])
      ....:             i += 1
      ....:         return my_poly(L)
      ....:     def __mul__(self, other):
      ....:         L, i = [], 0
      ....:         # as the definition goes
      ....:         for i in range(len(self.__coeffs) + len(other.__coeffs)-1):
      ....:             L.append(0)
      ....:             j = max(0, i-len(self.__coeffs)+2)
      ....:             while j <= i and j < len(self.__coeffs):
      ....:                 L[i] += self.__coeffs[j]*other.__coeffs[i-j]
      ....:                 j += 1
      ....:         return my_poly(L)
      ....:     def __repr__(self):
      ....:         return str(self.__coeffs)
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_94 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.doctest(_sage_const_20 , r"""
      sage: class my_poly2(my_poly):
      ....:     def eval(self, x):
      ....:         y = 0
      ....:         for c in self._my_poly__coeffs:
      ....:             y = x*y + c
      ....:         return y
    
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_132 )
_st_.endofdoc()

